// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Api.Data.Dto.BlockDto", b =>
                {
                    b.Property<long>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idx");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<string>("MerkleRoot")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mrkl_root");

                    b.Property<long>("Nonce")
                        .HasColumnType("INTEGER")
                        .HasColumnName("nonce");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_hash");

                    b.HasKey("Index")
                        .HasName("p_k_block");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("i_x_block_hash");

                    b.ToTable("block");
                });

            modelBuilder.Entity("Api.Data.Dto.VoteDto", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<long>("BlockIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("block_index");

                    b.Property<int>("PartyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("party_id");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("signature");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<string>("VoterAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("voter_address");

                    b.Property<string>("VoterPubKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("voter_pub_key");

                    b.HasKey("Hash")
                        .HasName("p_k_vote");

                    b.HasIndex("BlockIndex")
                        .HasDatabaseName("i_x_vote_block_index");

                    b.HasIndex("VoterAddress")
                        .IsUnique()
                        .HasDatabaseName("i_x_vote_voter_address");

                    b.ToTable("vote");
                });

            modelBuilder.Entity("Api.Data.Dto.VoteDto", b =>
                {
                    b.HasOne("Api.Data.Dto.BlockDto", "Block")
                        .WithMany("Votes")
                        .HasForeignKey("BlockIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_vote_block_block_index");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("Api.Data.Dto.BlockDto", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
